// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconPause: typeof import('./src/components/IconPause.vue')['default']
    IconPlay: typeof import('./src/components/IconPlay.vue')['default']
    LoadingItem: typeof import('./src/components/LoadingItem.vue')['default']
    LrcItem: typeof import('./src/components/LrcItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongItem: typeof import('./src/components/SongItem.vue')['default']
  }
}
